# Generated by Django 4.2.6 on 2023-10-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki', '0004_auto_20231016_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
